version: "3"
services:
  roteador:
    image: router_image
    container_name: router1  # Nome do contêiner
    environment:
      - CONTAINER_NAME=router1  # Definindo a variável de ambiente
    ports:
      - "5000:5000"
    networks:
      - rede

networks:
  rede:
    driver: bridge
    database:
      image: postgres:latest
      container_name: database1
      environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
        POSTGRES_DB: mydatabase
      ports:
        - "5432:5432"
      networks:
        - rede

    webserver:
      image: nginx:latest
      container_name: webserver1
      ports:
        - "8080:80"
      networks:
        - rede

    app:
      image: python:3.9-slim
      container_name: app1
      volumes:
        - ./app:/usr/src/app
      working_dir: /usr/src/app
      command: python app.py
      depends_on:
        - database
      networks:
        - rede